interface ImportMetaEnv {
  MODE: string
  VITE_APP_FIREBASE_KEY: string
  VITE_APP_FIREBASE_DOMAIN: string
  VITE_APP_FIREBASE_DATABASE: string
  VITE_APP_FIREBASE_PROJECT_ID: string
  VITE_APP_FIREBASE_STORAGE_BUCKET: string
  VITE_APP_FIREBASE_SENDER_ID: string
  VITE_APP_FIREBASE_APPID: string
}
